// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/agent_steps.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_proto_agent_steps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_steps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_proto_agent_steps_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type ToolCallInfo struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	CallId        string                   `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName      string                   `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson string                   `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	Nested        *ToolCallInfo_NestedInfo `protobuf:"bytes,7,opt,name=nested,proto3" json:"nested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallInfo) Reset() {
	*x = ToolCallInfo{}
	mi := &file_proto_agent_steps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallInfo) ProtoMessage() {}

func (x *ToolCallInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_steps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallInfo.ProtoReflect.Descriptor instead.
func (*ToolCallInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_steps_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCallInfo) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCallInfo) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallInfo) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *ToolCallInfo) GetNested() *ToolCallInfo_NestedInfo {
	if x != nil {
		return x.Nested
	}
	return nil
}

type TrajectoryInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Unknown_3      int32                  `protobuf:"varint,3,opt,name=unknown_3,json=unknown3,proto3" json:"unknown_3,omitempty"`
	CascadeId      string                 `protobuf:"bytes,4,opt,name=cascade_id,json=cascadeId,proto3" json:"cascade_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrajectoryInfo) Reset() {
	*x = TrajectoryInfo{}
	mi := &file_proto_agent_steps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrajectoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrajectoryInfo) ProtoMessage() {}

func (x *TrajectoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_steps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrajectoryInfo.ProtoReflect.Descriptor instead.
func (*TrajectoryInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_steps_proto_rawDescGZIP(), []int{2}
}

func (x *TrajectoryInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TrajectoryInfo) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *TrajectoryInfo) GetUnknown_3() int32 {
	if x != nil {
		return x.Unknown_3
	}
	return 0
}

func (x *TrajectoryInfo) GetCascadeId() string {
	if x != nil {
		return x.CascadeId
	}
	return ""
}

type StepMetadata struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *Timestamp             `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SomeEnum  int32                  `protobuf:"varint,3,opt,name=some_enum,json=someEnum,proto3" json:"some_enum,omitempty"`
	ToolCall  *ToolCallInfo          `protobuf:"bytes,4,opt,name=tool_call,json=toolCall,proto3" json:"tool_call,omitempty"`
	// Field 5-11 observed but structure is complex
	StepId        string          `protobuf:"bytes,12,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Trajectory    *TrajectoryInfo `protobuf:"bytes,20,opt,name=trajectory,proto3" json:"trajectory,omitempty"`
	ToolSummary   string          `protobuf:"bytes,30,opt,name=tool_summary,json=toolSummary,proto3" json:"tool_summary,omitempty"`
	ToolAction    string          `protobuf:"bytes,31,opt,name=tool_action,json=toolAction,proto3" json:"tool_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepMetadata) Reset() {
	*x = StepMetadata{}
	mi := &file_proto_agent_steps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepMetadata) ProtoMessage() {}

func (x *StepMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_steps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepMetadata.ProtoReflect.Descriptor instead.
func (*StepMetadata) Descriptor() ([]byte, []int) {
	return file_proto_agent_steps_proto_rawDescGZIP(), []int{3}
}

func (x *StepMetadata) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StepMetadata) GetSomeEnum() int32 {
	if x != nil {
		return x.SomeEnum
	}
	return 0
}

func (x *StepMetadata) GetToolCall() *ToolCallInfo {
	if x != nil {
		return x.ToolCall
	}
	return nil
}

func (x *StepMetadata) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepMetadata) GetTrajectory() *TrajectoryInfo {
	if x != nil {
		return x.Trajectory
	}
	return nil
}

func (x *StepMetadata) GetToolSummary() string {
	if x != nil {
		return x.ToolSummary
	}
	return ""
}

func (x *StepMetadata) GetToolAction() string {
	if x != nil {
		return x.ToolAction
	}
	return ""
}

type UserMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Unknown_1       string                 `protobuf:"bytes,1,opt,name=unknown_1,json=unknown1,proto3" json:"unknown_1,omitempty"`
	TextContent_2   string                 `protobuf:"bytes,2,opt,name=text_content_2,json=textContent2,proto3" json:"text_content_2,omitempty"`
	NestedContent_3 *UserMessage_Content   `protobuf:"bytes,3,opt,name=nested_content_3,json=nestedContent3,proto3" json:"nested_content_3,omitempty"` // Fields 4-18 omitted
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_proto_agent_steps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_steps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_steps_proto_rawDescGZIP(), []int{4}
}

func (x *UserMessage) GetUnknown_1() string {
	if x != nil {
		return x.Unknown_1
	}
	return ""
}

func (x *UserMessage) GetTextContent_2() string {
	if x != nil {
		return x.TextContent_2
	}
	return ""
}

func (x *UserMessage) GetNestedContent_3() *UserMessage_Content {
	if x != nil {
		return x.NestedContent_3
	}
	return nil
}

type AssistantMessage struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	TextContent   string                          `protobuf:"bytes,1,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	BotId         string                          `protobuf:"bytes,6,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	ToolDirective *AssistantMessage_ToolDirective `protobuf:"bytes,7,opt,name=tool_directive,json=toolDirective,proto3" json:"tool_directive,omitempty"`
	Thought_8     string                          `protobuf:"bytes,8,opt,name=thought_8,json=thought8,proto3" json:"thought_8,omitempty"`
	Unknown_12    int32                           `protobuf:"varint,12,opt,name=unknown_12,json=unknown12,proto3" json:"unknown_12,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantMessage) Reset() {
	*x = AssistantMessage{}
	mi := &file_proto_agent_steps_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantMessage) ProtoMessage() {}

func (x *AssistantMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_steps_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantMessage.ProtoReflect.Descriptor instead.
func (*AssistantMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_steps_proto_rawDescGZIP(), []int{5}
}

func (x *AssistantMessage) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *AssistantMessage) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *AssistantMessage) GetToolDirective() *AssistantMessage_ToolDirective {
	if x != nil {
		return x.ToolDirective
	}
	return nil
}

func (x *AssistantMessage) GetThought_8() string {
	if x != nil {
		return x.Thought_8
	}
	return ""
}

func (x *AssistantMessage) GetUnknown_12() int32 {
	if x != nil {
		return x.Unknown_12
	}
	return 0
}

type ToolOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolOutput) Reset() {
	*x = ToolOutput{}
	mi := &file_proto_agent_steps_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolOutput) ProtoMessage() {}

func (x *ToolOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_steps_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolOutput.ProtoReflect.Descriptor instead.
func (*ToolOutput) Descriptor() ([]byte, []int) {
	return file_proto_agent_steps_proto_rawDescGZIP(), []int{6}
}

func (x *ToolOutput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ToolOutput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Step struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StepType         int32                  `protobuf:"varint,1,opt,name=step_type,json=stepType,proto3" json:"step_type,omitempty"`
	Status           int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Metadata         *StepMetadata          `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserMessage      *UserMessage           `protobuf:"bytes,19,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	AssistantMessage *AssistantMessage      `protobuf:"bytes,20,opt,name=assistant_message,json=assistantMessage,proto3" json:"assistant_message,omitempty"`
	ToolOutput       *ToolOutput            `protobuf:"bytes,133,opt,name=tool_output,json=toolOutput,proto3" json:"tool_output,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_proto_agent_steps_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_steps_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_proto_agent_steps_proto_rawDescGZIP(), []int{7}
}

func (x *Step) GetStepType() int32 {
	if x != nil {
		return x.StepType
	}
	return 0
}

func (x *Step) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Step) GetMetadata() *StepMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Step) GetUserMessage() *UserMessage {
	if x != nil {
		return x.UserMessage
	}
	return nil
}

func (x *Step) GetAssistantMessage() *AssistantMessage {
	if x != nil {
		return x.AssistantMessage
	}
	return nil
}

func (x *Step) GetToolOutput() *ToolOutput {
	if x != nil {
		return x.ToolOutput
	}
	return nil
}

// Fields 4-6 omitted as they are complex/unknown
type ToolCallInfo_NestedInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallInfo_NestedInfo) Reset() {
	*x = ToolCallInfo_NestedInfo{}
	mi := &file_proto_agent_steps_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallInfo_NestedInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallInfo_NestedInfo) ProtoMessage() {}

func (x *ToolCallInfo_NestedInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_steps_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallInfo_NestedInfo.ProtoReflect.Descriptor instead.
func (*ToolCallInfo_NestedInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_steps_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ToolCallInfo_NestedInfo) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserMessage_Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawText       string                 `protobuf:"bytes,1,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessage_Content) Reset() {
	*x = UserMessage_Content{}
	mi := &file_proto_agent_steps_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage_Content) ProtoMessage() {}

func (x *UserMessage_Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_steps_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage_Content.ProtoReflect.Descriptor instead.
func (*UserMessage_Content) Descriptor() ([]byte, []int) {
	return file_proto_agent_steps_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UserMessage_Content) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

type AssistantMessage_ToolDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgsJson      string                 `protobuf:"bytes,3,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantMessage_ToolDirective) Reset() {
	*x = AssistantMessage_ToolDirective{}
	mi := &file_proto_agent_steps_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantMessage_ToolDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantMessage_ToolDirective) ProtoMessage() {}

func (x *AssistantMessage_ToolDirective) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_steps_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantMessage_ToolDirective.ProtoReflect.Descriptor instead.
func (*AssistantMessage_ToolDirective) Descriptor() ([]byte, []int) {
	return file_proto_agent_steps_proto_rawDescGZIP(), []int{5, 0}
}

func (x *AssistantMessage_ToolDirective) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *AssistantMessage_ToolDirective) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *AssistantMessage_ToolDirective) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

var File_proto_agent_steps_proto protoreflect.FileDescriptor

const file_proto_agent_steps_proto_rawDesc = "" +
	"\n" +
	"\x17proto/agent_steps.proto\x12\ragent.history\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\"\xcd\x01\n" +
	"\fToolCallInfo\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\x12>\n" +
	"\x06nested\x18\a \x01(\v2&.agent.history.ToolCallInfo.NestedInfoR\x06nested\x1a \n" +
	"\n" +
	"NestedInfo\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x94\x01\n" +
	"\x0eTrajectoryInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\x12\x1b\n" +
	"\tunknown_3\x18\x03 \x01(\x05R\bunknown3\x12\x1d\n" +
	"\n" +
	"cascade_id\x18\x04 \x01(\tR\tcascadeId\"\xb9\x02\n" +
	"\fStepMetadata\x126\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x18.agent.history.TimestampR\ttimestamp\x12\x1b\n" +
	"\tsome_enum\x18\x03 \x01(\x05R\bsomeEnum\x128\n" +
	"\ttool_call\x18\x04 \x01(\v2\x1b.agent.history.ToolCallInfoR\btoolCall\x12\x17\n" +
	"\astep_id\x18\f \x01(\tR\x06stepId\x12=\n" +
	"\n" +
	"trajectory\x18\x14 \x01(\v2\x1d.agent.history.TrajectoryInfoR\n" +
	"trajectory\x12!\n" +
	"\ftool_summary\x18\x1e \x01(\tR\vtoolSummary\x12\x1f\n" +
	"\vtool_action\x18\x1f \x01(\tR\n" +
	"toolAction\"\xc4\x01\n" +
	"\vUserMessage\x12\x1b\n" +
	"\tunknown_1\x18\x01 \x01(\tR\bunknown1\x12$\n" +
	"\x0etext_content_2\x18\x02 \x01(\tR\ftextContent2\x12L\n" +
	"\x10nested_content_3\x18\x03 \x01(\v2\".agent.history.UserMessage.ContentR\x0enestedContent3\x1a$\n" +
	"\aContent\x12\x19\n" +
	"\braw_text\x18\x01 \x01(\tR\arawText\"\xc2\x02\n" +
	"\x10AssistantMessage\x12!\n" +
	"\ftext_content\x18\x01 \x01(\tR\vtextContent\x12\x15\n" +
	"\x06bot_id\x18\x06 \x01(\tR\x05botId\x12T\n" +
	"\x0etool_directive\x18\a \x01(\v2-.agent.history.AssistantMessage.ToolDirectiveR\rtoolDirective\x12\x1b\n" +
	"\tthought_8\x18\b \x01(\tR\bthought8\x12\x1d\n" +
	"\n" +
	"unknown_12\x18\f \x01(\x05R\tunknown12\x1ab\n" +
	"\rToolDirective\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x1b\n" +
	"\targs_json\x18\x03 \x01(\tR\bargsJson\"8\n" +
	"\n" +
	"ToolOutput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\xbe\x02\n" +
	"\x04Step\x12\x1b\n" +
	"\tstep_type\x18\x01 \x01(\x05R\bstepType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x127\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1b.agent.history.StepMetadataR\bmetadata\x12=\n" +
	"\fuser_message\x18\x13 \x01(\v2\x1a.agent.history.UserMessageR\vuserMessage\x12L\n" +
	"\x11assistant_message\x18\x14 \x01(\v2\x1f.agent.history.AssistantMessageR\x10assistantMessage\x12;\n" +
	"\vtool_output\x18\x85\x01 \x01(\v2\x19.agent.history.ToolOutputR\n" +
	"toolOutputB'Z%github.com/hollykbuck/agchatexport/pbb\x06proto3"

var (
	file_proto_agent_steps_proto_rawDescOnce sync.Once
	file_proto_agent_steps_proto_rawDescData []byte
)

func file_proto_agent_steps_proto_rawDescGZIP() []byte {
	file_proto_agent_steps_proto_rawDescOnce.Do(func() {
		file_proto_agent_steps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_steps_proto_rawDesc), len(file_proto_agent_steps_proto_rawDesc)))
	})
	return file_proto_agent_steps_proto_rawDescData
}

var file_proto_agent_steps_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_agent_steps_proto_goTypes = []any{
	(*Timestamp)(nil),                      // 0: agent.history.Timestamp
	(*ToolCallInfo)(nil),                   // 1: agent.history.ToolCallInfo
	(*TrajectoryInfo)(nil),                 // 2: agent.history.TrajectoryInfo
	(*StepMetadata)(nil),                   // 3: agent.history.StepMetadata
	(*UserMessage)(nil),                    // 4: agent.history.UserMessage
	(*AssistantMessage)(nil),               // 5: agent.history.AssistantMessage
	(*ToolOutput)(nil),                     // 6: agent.history.ToolOutput
	(*Step)(nil),                           // 7: agent.history.Step
	(*ToolCallInfo_NestedInfo)(nil),        // 8: agent.history.ToolCallInfo.NestedInfo
	(*UserMessage_Content)(nil),            // 9: agent.history.UserMessage.Content
	(*AssistantMessage_ToolDirective)(nil), // 10: agent.history.AssistantMessage.ToolDirective
}
var file_proto_agent_steps_proto_depIdxs = []int32{
	8,  // 0: agent.history.ToolCallInfo.nested:type_name -> agent.history.ToolCallInfo.NestedInfo
	0,  // 1: agent.history.StepMetadata.timestamp:type_name -> agent.history.Timestamp
	1,  // 2: agent.history.StepMetadata.tool_call:type_name -> agent.history.ToolCallInfo
	2,  // 3: agent.history.StepMetadata.trajectory:type_name -> agent.history.TrajectoryInfo
	9,  // 4: agent.history.UserMessage.nested_content_3:type_name -> agent.history.UserMessage.Content
	10, // 5: agent.history.AssistantMessage.tool_directive:type_name -> agent.history.AssistantMessage.ToolDirective
	3,  // 6: agent.history.Step.metadata:type_name -> agent.history.StepMetadata
	4,  // 7: agent.history.Step.user_message:type_name -> agent.history.UserMessage
	5,  // 8: agent.history.Step.assistant_message:type_name -> agent.history.AssistantMessage
	6,  // 9: agent.history.Step.tool_output:type_name -> agent.history.ToolOutput
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_agent_steps_proto_init() }
func file_proto_agent_steps_proto_init() {
	if File_proto_agent_steps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_steps_proto_rawDesc), len(file_proto_agent_steps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_agent_steps_proto_goTypes,
		DependencyIndexes: file_proto_agent_steps_proto_depIdxs,
		MessageInfos:      file_proto_agent_steps_proto_msgTypes,
	}.Build()
	File_proto_agent_steps_proto = out.File
	file_proto_agent_steps_proto_goTypes = nil
	file_proto_agent_steps_proto_depIdxs = nil
}
